In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
df=pd.read_csv('./chipotle.tsv',sep='\t')

In [59]:
df.shape

(4622, 5)

In [60]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [61]:
df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [62]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [63]:
c=df.groupby('item_name').sum()
c=c.sort_values(['quantity'],ascending=False)
c.head(1)
df.info()
df['item_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [64]:
df['item_price'].head()

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: item_price, dtype: float64

In [65]:

df.groupby('item_name').sum().sort_values(['quantity'],ascending=False).head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",7342.73

In [66]:
df.groupby('choice_description').sum().sort_values(['quantity'],ascending=False).head(1)

,order_id,quantity,item_name,item_price
choice_description,,,,
[Diet Coke],123455,159,Canned SodaCanned SodaCanned Soda6 Pack Soft D...,326.71

In [72]:
df.quantity.sum()
df.order_id.dtype

dtype('int64')

In [68]:
# key=lambda x:float(x[1:-1])
# df.item_price=df.item_price.apply(key)
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [69]:
df['revenue']=df['quantity']*df['item_price']
df['revenue'].sum()

np.float64(39237.02)

In [70]:
df.order_id.value_counts().count()

np.int64(1834)

In [74]:
x=df.groupby('order_id').sum()
print(x['revenue'].mean())

21.39423118865867

In [75]:
len(df[df.item_price>10.00])

1130

In [77]:
filtered=df.drop_duplicates(['item_name','choice_description'])
filtered

,order_id,quantity,item_name,choice_description,item_price,revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
...,...,...,...,...,...,...
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25,9.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75,11.75
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25,9.25

In [81]:
filtered=filtered.loc[filtered['item_price']>10.0 ,['item_price']].reset_index(drop=True)
filtered

     item_price
0         16.98
1         10.98
2         11.75
3         11.25
4         10.98
..          ...
754       11.75
755       11.75
756       11.75
757       11.75
758       11.25

[759 rows x 1 columns]

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.